### ISSUE TITLE
Oldest image doesn't download

### ISSUE THREAD

**Issue by danieman** [akurtovic/InstaRaider#30]
Hi,
just wanted to let you know that there is an error in the program that causes the oldest photo not to be downloaded. It correctly retrieves the number of posts, but when it starts downloading, the profile picture counts as 1. This means that the oldest photo doesn't get in the counter.

Example:
User has 3 posts.
InstaRaider downloads photo 1/3. (profile pic)
InstaRaider downloads photo 2/3. (newest post)
InstaRaider downloads photo 3/3. (second newest post)
loop terminates (oldest post is not downloaded).

It was an easy fix, and I've fixed it for myself, but I thought you'd like to know so you could change the program too. :-)

**Comment by boomshadow** [comment]
@danieman You should submit a pull request with your fix. That way you can help out the project :) I'm not an admin of this project, but I'd sure like to have your fix as well. heh heh

**Comment by danieman** [comment]
My fix was far from pretty. I just incremented the loop limit by 1. I'm sure people want a better fix than that, haha. Also, I'm new to github, and I have no idea what a pull request is and how to do it. :-/

**Comment by boomshadow** [comment]
That sounds like a good fix actually. I'd say you should commit that so you can have the credit for fixing the bug. Just hit the fork button in the top right of the screen (while you're viewing this project), and it'll fork the project to your account.

Next, clone it down to your computer, create a new branch naming it after the feature. Such as "fix-oldest-image-download" or something like that.

Make your code change, push it up to your Github, and then hit the button for "create a pull request". Github will make it pretty obvious about the pull request because it sees you made a change to the project.

**Comment by rainbowhat** [comment]
Do you face any issue downloading it? Like there is 1million images. Cant expect instagram to allow us to download all with one IP? or does it not matter?
