### ISSUE TITLE
Error: File "instaRaider.py", line 21, in <module>

### ISSUE THREAD

**Issue by otrapersona** [akurtovic/InstaRaider#32]
This happened:

human@afterall:~$ python ~/InstaRaider/instaRaider.py example ~/Pictures/example
Traceback (most recent call last):
  File "/home/human/InstaRaider/instaRaider.py", line 21, in <module>
    from urllib3.exceptions import InsecurePlatformWarning
ImportError: cannot import name InsecurePlatformWarning

**Comment by akurtovic** [comment]
Sorry I'm just getting to this now. Have you figured it out? I can't help without more info, but it looks like it's you just need to try reinstalling the urllib3 module (pip install urllib3).

**Comment by error454** [comment]
I encountered this same issue on latest ubuntu. The problem was that the platform installed version of the urllib3 and requests modules were out of date by about 3 major versions. To fix the problem I had to remove the platform installed versions of those files:

    sudo apt-get remove python-urllib3
    sudo apt-get remove python-requests

Then use pip to install the updated versions:

    sudo pip install urllib3 --upgrade
    sudo pip install requests --upgrade

**Comment by akurtovic** [comment]
@error454 Thanks for the info. You should try that @otrapersona
