### ISSUE TITLE
Update README to reflect changes introduced in PR #34

### ISSUE THREAD

**Issue by akurtovic** [akurtovic/InstaRaider#35]
Update README to document the new meta feature introduced by https://github.com/akurtovic/InstaRaider/pull/34

**Comment by izilly** [comment]
I'll update README and submit another pull request.  

Since the dependencies and installation instructions are for Debian, I suppose I should add a line detailing how to install gexiv2 on a Debian system but I don't have one installed.  

I assume this would work but I'm not sure:
`sudo apt-get install gexiv2`

Is that right?

**Comment by freeman212** [comment]
@izilly 
`sudo apt-get install gir1.2-gexiv2-0.10`
worked for me
