### ISSUE TITLE
Find a way to sort photos by date.

### ISSUE THREAD

**Issue by LVLAaron** [akurtovic/InstaRaider#61]
It would be nice if there were a way to name the files when being stored locally so they can be sorted the same way they appear on instragram.

**Comment by makudesu** [comment]
The program saves the files using the names provided by instagram(i think photo_name), then the next time you download, it compares the already downloaded files and instagram's photos using the photo_name and then skips if true(self.log('Skipping file', photo_name, 'as it already exists.')). changing the name might break this and might need to use the caption and/or date_time rather than photo_name(this clearly needs some modifications to the existing code and might introduce some bugs because of lack of unit tests, all this in exchange for cooler name which is in my opinion not necessary). my suggestion is just right click the folder and sort by date.
