### ISSUE TITLE
Possible issue with your current naming method.

### ISSUE THREAD

**Issue by dannyvoid** [akurtovic/InstaRaider#9]
Came across a possible issue..
If you use the current photo naming method in your script there's a possibility to lose photos, because username_10.jpg today, can be a different than username_10.jpg from last week, if you've uploaded an image, and deleted one.

My personal fix is to just keep the original file name that Instagram supplies.
Not using a pull request to show this, because I just want you to know of a possible issue, and my code isn't the best.

                rawUrl = re.search('https.+;', str(photoDiv));
                photoUrl = str(rawUrl.group(0))[:-2]
                split = urlparse.urlsplit(photoUrl)
                photoName = directory + split.path.split("/")[-1]

                # save full-resolution photo
                urllib.urlretrieve(photoUrl, photoName)

**Comment by akurtovic** [comment]
I agree with you that the current naming system is not ideal. I originally built this out of a frustration with trying to download all of my own photos from Instagram after switching from an Android to an iPhone, so the thinking was that this was something I would run once and have all of my photos. But a different naming scheme does make sense if you are going to run this periodically to download all photos, or just the latest photos.

I like your idea and I think you should make a pull request with one minor change. Instead of saving the photo each time, I think it would be better if you loop through all of the photos that are already in the directory and only save the photo if it doesn't exist yet. That way you would still retain a history of when the photo was saved to the directory.

Let me know if you want to make that small modification and create a pull request. If not, I still appreciate the idea and when I have some time to work on this in the future I'll make the change myself. I'll keep this issue open until the change is implemented.

**Comment by dannyvoid** [comment]
Created the pull request with the modifications!
